feat: bvh
andrewgazelka/hyperion pull request #111
Opened 2024-04-03 04:01 UTC by andrewgazelka

still need a lot of work

2024-04-04 13:07 UTC, TestingPlant requested changes

2024-04-04 15:59 UTC, andrewgazelka commented on crates/bvh/src/aabb.rs
> +            acc.expand_to_fit(&aabb);
I am already using multi-threading when building the BVH, but I could see it being useful if `containing` contributes mainly to the runtime for the first (or few) nodes before there are multiple threads.

I refactored to use SIMD
https://github.com/andrewgazelka/hyperion/blob/f8153afd021d55afbd4af37ff0eff2aea8a78e7f/crates/bvh/src/aabb.rs#L168-L202

From what I can tell, this adds about a 30% improvement to building the tree.

2024-04-04 16:05 UTC, andrewgazelka commented on crates/bvh/src/lib.rs
> +    elems: Vec<SmallVec<T, MAX_ELEMENTS_PER_LEAF>>,
b0982b9

ok I agree. I was using SmallVec originally because I was thinking we might have an insertion operation before we rebuild but let's keep it at arrayvec until this is added.

2024-04-04 16:05 UTC, andrewgazelka commented on crates/bvh/src/lib.rs
> +    elems: Vec<SmallVec<T, MAX_ELEMENTS_PER_LEAF>>,
b0982b9

ok I agree. I was using SmallVec originally because I was thinking we might have an insertion operation before we rebuild but let's keep it at arrayvec until this is added.

2024-04-04 16:07 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        let head_idx = self.head.fetch_add(1, Ordering::Relaxed);
Yea I so I made `pop` not public which is originally how I designed it. I think it is fine now?

2024-04-04 16:24 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
perhaps .. I think the benefit I have now is I can easily (with essentially a nop) turn the `Queue` collection into an `Vec<T>` .

However, in the future probably want to get a new data structure because atomics still "kinda" have contention it looks like (probably something with cache)

```
├─ build_1m_rayon                     │               │               │               │         │
│  ╰─ TrivialHeuristic                │               │               │               │         │
│     ├─ 1              55.48 ms      │ 66.47 ms      │ 57.49 ms      │ 57.65 ms      │ 100     │ 100
│     │                 18.02 Mitem/s │ 15.04 Mitem/s │ 17.39 Mitem/s │ 17.34 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 1             │ 0             │ 0.01          │         │
│     │                   0 B         │ 1.52 KB       │ 0 B           │ 15.2 B        │         │
│     ├─ 2              32.25 ms      │ 34.94 ms      │ 33.04 ms      │ 33.15 ms      │ 100     │ 100
│     │                 31 Mitem/s    │ 28.61 Mitem/s │ 30.26 Mitem/s │ 30.16 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 0             │ 0             │ 0.01          │         │
│     │                   0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
│     ├─ 4              19.74 ms      │ 22.62 ms      │ 21.03 ms      │ 21.06 ms      │ 100     │ 100
│     │                 50.63 Mitem/s │ 44.2 Mitem/s  │ 47.53 Mitem/s │ 47.47 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 0             │ 0             │ 0.01          │         │
│     │                   0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
│     ╰─ 8              17.03 ms      │ 29.47 ms      │ 17.71 ms      │ 18.03 ms      │ 100     │ 100
│                       58.69 Mitem/s │ 33.92 Mitem/s │ 56.43 Mitem/s │ 55.43 Mitem/s │         │
│                       alloc:        │               │               │               │         │
│                         0           │ 0             │ 0             │ 0.01          │         │
│                         0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
```

2024-04-04 17:41 UTC, andrewgazelka commented
I'm doing some more tests and the BVH is definitely badly broken

2024-04-04 18:04 UTC, andrewgazelka commented
![test](https://github.com/andrewgazelka/hyperion/assets/7644264/568cf7e9-a8c1-4336-99bc-96ea6a5be6ac)

2024-04-04 18:31 UTC, TestingPlant commented on crates/bvh/src/queue.rs
> +        let head_idx = self.head.fetch_add(1, Ordering::Relaxed);
If it's converted to a Vec after this fetch_add and before the write, it's still reading uninit memory. I can try writing the impl in a few hours

2024-04-04 18:31 UTC, TestingPlant commented on crates/bvh/src/queue.rs
> +        self.head.store(head, Ordering::Relaxed);
I'd suggest removing this function and making the Drop impl on Queue iterate through all elements, call drop on them, and then free the memory

2024-04-04 18:47 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        let head_idx = self.head.fetch_add(1, Ordering::Relaxed);
https://github.com/andrewgazelka/hyperion/blob/1045baeb718c2f02b02d4beb1855cb359a13599d/crates/bvh/src/queue.rs#L71-L80

I don't think this can happen because `pub fn into_inner(self)` requires `self` so it cannot be executed until all shared references (`push`) are finished.

2024-04-04 19:32 UTC, TestingPlant requested changes

2024-04-04 19:32 UTC, TestingPlant commented on crates/bvh/src/queue.rs
> +        let head_idx = self.head.fetch_add(1, Ordering::Relaxed);
That's true, I think using relaxed is fine then. Should have a bounds check though

2024-04-04 19:32 UTC, TestingPlant commented on crates/bvh/src/queue.rs
> +
Why's this outside of `Queue::new_in`?

2024-04-04 20:41 UTC, andrewgazelka commented on crates/bvh/src/aabb.rs
> +            let min = Simd::<f32, 4>::from_slice(min);
well I don't think it would be out of bounds because there is something on the stack directly before it. anyway, I am removing this for now because I think it potentially caused issues

b40b77e

2024-04-04 20:41 UTC, andrewgazelka commented on crates/bvh/src/aabb.rs
> +unsafe impl bytemuck::Pod for Aabb {}
b40b77e

2024-04-04 20:43 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +
70ae233

2024-04-04 20:43 UTC, andrewgazelka commented on crates/bvh/src/aabb.rs
> +            acc.expand_to_fit(&aabb);
actually I removed SIMD for now

2024-04-04 20:52 UTC, TestingPlant commented on crates/bvh/src/aabb.rs
> +            let min = Simd::<f32, 4>::from_slice(min);
LLVM can still optimize out the code or replace it with ud2 which stops the program. Since it's being removed I'll resolve the thread

2024-04-04 23:36 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        let head_idx = self.head.fetch_add(1, Ordering::Relaxed);
6457f4b

2024-04-04 23:37 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        self.head.store(head, Ordering::Relaxed);
7730121

2024-04-05 00:13 UTC, TestingPlant commented on crates/bvh/src/queue.rs
> +        self.head.store(head, Ordering::Relaxed);
I meant that, in the drop impl, you can fetch head once to get the len, make a slice of ManuallyDrop<T>, and call drop on all the data. I guess the change there is fine though so you can resolve this thread if your want

2024-04-05 03:44 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        self.head.store(head, Ordering::Relaxed);
ahhhh yes that would be better

2024-04-05 05:26 UTC, andrewgazelka commented
c1c7c66

I get these timings (atomics are removed so the building can scale). However, the buffer must be about twice as big to do this, slightly reducing performance when checking for collisions.

```
Timer precision: 41 ns
bvh                     fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ build                              │               │               │               │         │
│  ╰─ TrivialHeuristic                │               │               │               │         │
│     ├─ 100            10.12 µs      │ 408.8 µs      │ 29.72 µs      │ 43.13 µs      │ 100     │ 100
│     │                 9.877 Mitem/s │ 244.5 Kitem/s │ 3.363 Mitem/s │ 2.318 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   2           │ 0             │ 2             │ 1.99          │         │
│     │                   3.936 KB    │ 0 B           │ 3.936 KB      │ 3.911 KB      │         │
│     ├─ 1000           43.24 µs      │ 212.9 µs      │ 62.49 µs      │ 73.11 µs      │ 100     │ 100
│     │                 23.12 Mitem/s │ 4.695 Mitem/s │ 16 Mitem/s    │ 13.67 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   2           │ 2             │ 2             │ 2.02          │         │
│     │                   39.87 KB    │ 39.87 KB      │ 40.63 KB      │ 39.9 KB       │         │
│     ╰─ 10000          130.2 µs      │ 455.2 µs      │ 233.6 µs      │ 240.8 µs      │ 100     │ 100
│                       76.75 Mitem/s │ 21.96 Mitem/s │ 42.8 Mitem/s  │ 41.52 Mitem/s │         │
│                       alloc:        │               │               │               │         │
│                         2           │ 2             │ 2             │ 2.01          │         │
│                         400 KB      │ 400 KB        │ 400 KB        │ 400 KB        │         │
├─ build_1m_rayon                     │               │               │               │         │
│  ╰─ TrivialHeuristic                │               │               │               │         │
│     ├─ 1              63.14 ms      │ 68.53 ms      │ 64.46 ms      │ 64.65 ms      │ 100     │ 100
│     │                 15.83 Mitem/s │ 14.59 Mitem/s │ 15.51 Mitem/s │ 15.46 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 0             │ 0             │ 0.01          │         │
│     │                   0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
│     ├─ 2              34.06 ms      │ 45.16 ms      │ 34.78 ms      │ 35.12 ms      │ 100     │ 100
│     │                 29.35 Mitem/s │ 22.14 Mitem/s │ 28.74 Mitem/s │ 28.46 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 0             │ 0             │ 0.01          │         │
│     │                   0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
│     ├─ 4              20.47 ms      │ 26.96 ms      │ 21.1 ms       │ 21.2 ms       │ 100     │ 100
│     │                 48.83 Mitem/s │ 37.08 Mitem/s │ 47.38 Mitem/s │ 47.16 Mitem/s │         │
│     │                 alloc:        │               │               │               │         │
│     │                   0           │ 0             │ 0             │ 0.01          │         │
│     │                   0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
│     ╰─ 8              13.92 ms      │ 19.34 ms      │ 14.79 ms      │ 14.91 ms      │ 100     │ 100
│                       71.81 Mitem/s │ 51.7 Mitem/s  │ 67.59 Mitem/s │ 67.03 Mitem/s │         │
│                       alloc:        │               │               │               │         │
│                         0           │ 0             │ 0             │ 0.01          │         │
│                         0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
├─ query                              │               │               │               │         │
│  ╰─ TrivialHeuristic                │               │               │               │         │
│     ├─ 100            3.957 µs      │ 7.499 µs      │ 4.478 µs      │ 4.586 µs      │ 100     │ 100
│     │                 25.26 Mitem/s │ 13.33 Mitem/s │ 22.32 Mitem/s │ 21.8 Mitem/s  │         │
│     ├─ 1000           82.91 µs      │ 110.3 µs      │ 88.2 µs       │ 88.67 µs      │ 100     │ 100
│     │                 12.06 Mitem/s │ 9.06 Mitem/s  │ 11.33 Mitem/s │ 11.27 Mitem/s │         │
│     ╰─ 10000          1.512 ms      │ 1.837 ms      │ 1.648 ms      │ 1.661 ms      │ 100     │ 100
│                       6.613 Mitem/s │ 5.441 Mitem/s │ 6.064 Mitem/s │ 6.017 Mitem/s │         │
╰─ query_par                          │               │               │               │         │
   ╰─ TrivialHeuristic                │               │               │               │         │
      ├─ 100            29.2 µs       │ 152.5 µs      │ 49.79 µs      │ 56.53 µs      │ 100     │ 100
      │                 3.423 Mitem/s │ 655.5 Kitem/s │ 2.008 Mitem/s │ 1.768 Mitem/s │         │
      │                 alloc:        │               │               │               │         │
      │                   0           │ 0             │ 0             │ 0.02          │         │
      │                   0 B         │ 0 B           │ 0 B           │ 30.4 B        │         │
      ├─ 1000           72.7 µs       │ 219.4 µs      │ 102.9 µs      │ 108.1 µs      │ 100     │ 100
      │                 13.75 Mitem/s │ 4.555 Mitem/s │ 9.716 Mitem/s │ 9.249 Mitem/s │         │
      │                 alloc:        │               │               │               │         │
      │                   0           │ 0             │ 0             │ 0.02          │         │
      │                   0 B         │ 0 B           │ 0 B           │ 30.4 B        │         │
      ╰─ 10000          374.3 µs      │ 679.6 µs      │ 445.7 µs      │ 460.4 µs      │ 100     │ 100
                        26.71 Mitem/s │ 14.71 Mitem/s │ 22.43 Mitem/s │ 21.71 Mitem/s │         │
                        alloc:        │               │               │               │         │
                          0           │ 0             │ 0             │ 0.01          │         │
                          0 B         │ 0 B           │ 0 B           │ 15.2 B        │         │
```

2024-04-05 05:48 UTC, andrewgazelka commented
7bf3df7 compared to itself. You can see how very dense BVH makes finding collisions very expensive (since it is colliding with nearly everything)


```
build_sparse_bvh                                   [ 256.2 us ... 265.4 us ]      +3.57%
build_dense_bvh                                    [ 223.7 us ... 235.6 us ]      +5.31%
build_very_dense_bvh                               [ 223.5 us ... 226.4 us ]      +1.29%
collisions_sparse_bvh                              [ 214.6 us ... 239.4 us ]     +11.59%
collisions_dense_bvh                               [ 300.0 us ... 312.0 us ]      +3.98%
collisions_very_dense_bvh                          [  26.0 ms ...  27.4 ms ]      +5.41%
```

https://github.com/andrewgazelka/hyperion/blob/7bf3df7a54b372784276465d57fe717b37c7baa6/crates/bvh/benches/side_by_side.rs#L31-L37

2024-04-05 06:01 UTC, andrewgazelka commented
d9ccdb6

Added max collisions (ability to short circuit). this actually improves it a bit for really dense situations. This is compared to itself btw.

```
build_sparse_bvh                                   [ 250.4 us ... 247.6 us ]      -1.12%
build_dense_bvh                                    [ 247.1 us ... 245.0 us ]      -0.85%
build_very_dense_bvh                               [ 237.8 us ... 238.8 us ]      +0.41%
collisions_sparse_bvh                              [ 217.9 us ... 221.4 us ]      +1.59%
collisions_dense_bvh                               [ 280.6 us ... 284.0 us ]      +1.24%
collisions_very_dense_bvh                          [  23.7 ms ...  24.0 ms ]      +1.39%
collisions_very_dense_bvh_limited                  [   8.0 ms ...   7.9 ms ]      -0.09%
```

2024-04-05 06:08 UTC, andrewgazelka commented
adding `VOLUME_TO_ACTIVATE_LEAF` helps for very dense situations :)

```
build_sparse_bvh                                   [ 268.9 us ... 265.9 us ]      -1.08%
build_dense_bvh                                    [ 248.4 us ... 250.9 us ]      +0.99%
build_very_dense_bvh                               [ 223.0 us ... 104.3 us ]     -53.24%*
collisions_sparse_bvh                              [ 215.1 us ... 216.0 us ]      +0.40%
collisions_dense_bvh                               [ 319.2 us ... 314.0 us ]      -1.65%
collisions_very_dense_bvh                          [  26.5 ms ...  19.7 ms ]     -25.65%*
collisions_very_dense_bvh_limited                  [   8.2 ms ... 131.9 us ]     -98.39%*
```

2024-04-05 06:08 UTC, andrewgazelka commented on crates/bvh/src/queue.rs
> +        self.head.store(head, Ordering::Relaxed);
no longer applicable as I am not using this anymore.

2024-04-05 06:18 UTC, andrewgazelka commented
having max collisions improves _a lot_, but now zombies can make something that is very close to a point mass. Ideally I think zombies would

- sample `n` random points colliding with its AABB
- scale the velocity by `N/n` where `N` is the total number of entities in AABB.

![CleanShot 2024-04-05 at 01 16 14@2x](https://github.com/andrewgazelka/hyperion/assets/7644264/c66d08c3-f59c-4275-bb78-1c7d6fa0e80b)

2024-04-05 14:27 UTC, andrewgazelka commented
todo: add `get_all_collisions` which I think can be faster than individually calling `get_collision`

2024-04-07 01:24 UTC, herin049 approved these changes

2024-04-07 01:24 UTC, herin049 commented on crates/bvh/src/aabb.rs
> +        let max_y = a.max.y.min(b.max.y);
Why no `z` component?

2024-04-07 01:27 UTC, andrewgazelka commented on crates/bvh/src/aabb.rs
> +        let max_y = a.max.y.min(b.max.y);
8d95ce2

good catch

2024-04-07 01:36 UTC, herin049 approved these changes

2024-04-07 02:24 UTC, merged

2024-04-07 02:32 UTC, TestingPlant commented on crates/server/src/lib.rs
> +            exclude_player: None, // todo: include player
On my machine, when having bots randomly move, they look like they're struggling to move. I think exclude_player not being used causes this since they're being updated to their position from about 1 tick ago. I don't know why this glitchiness doesn't occur in the regular client though

2024-04-07 02:34 UTC, TestingPlant commented on crates/bvh/src/lib.rs
> +        max_threads: usize,
Nevermind I skimmed over the if statement

2024-04-07 04:17 UTC, andrewgazelka commented on crates/server/src/lib.rs
> +                    spin_sleep::sleep(wait_duration);
meh you are probably right...

btw `spin_sleep` doesn't spin the whole way... only the last little bit for precision.

2024-04-07 04:51 UTC, andrewgazelka commented on crates/server/src/lib.rs
> +            exclude_player: None, // todo: include player
1. it doesn't happen for your client but the bots could process it weird too

- [ ] code is small can check

2. this is how it looks for me

https://github.com/andrewgazelka/hyperion/assets/7644264/3fabc529-b24f-4910-8f8f-71e33a45e4f9

2024-04-07 04:52 UTC, andrewgazelka commented on crates/bvh/src/lib.rs
> +    }
I don't think so because only if `max_threads != max_threads_tentative` and it will if it is 1 I think