docs: add intro video (#61)
andrewgazelka/hyperion pull request #95
Opened 2024-04-01 21:54 UTC by TestingPlant

The README only includes an image of the video thumbnail that needs to be clicked, but there doesn't appear to a better way to embed videos.

2024-04-01 23:11 UTC, andrewgazelka requested changes

2024-04-01 23:11 UTC, andrewgazelka commented on README.md
> +[![Intro video](https://img.youtube.com/vi/hRc2oWAXd70/0.jpg)](https://www.youtube.com/watch?v=hRc2oWAXd70)
I think I would make it a clickable webm which is like a GIF but better compression. I have done this a few times so I can try to do it if you want :).

2024-04-01 23:15 UTC, TestingPlant commented on README.md
> +[![Intro video](https://img.youtube.com/vi/hRc2oWAXd70/0.jpg)](https://www.youtube.com/watch?v=hRc2oWAXd70)
You can add it as a webm

2024-04-13 17:36 UTC, andrewgazelka commented
closing for now

2024-04-13 17:36 UTC, closed without merging